In [1]:
from fetcher.YahooDataFetcher import YahooDataFetcher

In [2]:
fetcher = YahooDataFetcher(country="usa", tickers="^GSPC", interval="1d")

Deleted: ./data/usa/combined_output.csv
Deleted: ./data/usa/^GSPC_2020-01-30_2025-01-28_1d.csv
All files have been deleted.

In [3]:
fetcher.download_data()

Downloading data for ^GSPC...

[*********************100%***********************]  1 of 1 completed

Index(['Datetime', 'Close', 'High', 'Low', 'Open', 'Volume'], dtype='object', name='Price')
Data successfully saved to ./data/usa/^GSPC_2020-01-30_2025-01-28_1d.csv
All tickers Download complete.

/Users/mini/Desktop/Projects/FinDRL/fetcher/YahooDataFetcher.py:144: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_data['Ticker'] = ticker

In [4]:
data = fetcher.get_data()

All CSV files have been combined into ./data/usa/combined_output.csv

In [5]:
data

,Datetime,index,Open,High,Low,Close,Volume,Ticker
0,2020-01-30,0,3256.449951,3285.909912,3242.800049,3283.659912,3790350000,^GSPC
1,2020-01-31,1,3282.330078,3282.330078,3214.679932,3225.520020,4529700000,^GSPC
2,2020-02-03,2,3235.659912,3268.439941,3235.659912,3248.919922,3760460000,^GSPC
3,2020-02-04,3,3280.610107,3306.919922,3280.610107,3297.590088,3996900000,^GSPC
4,2020-02-05,4,3324.909912,3337.580078,3313.750000,3334.689941,4121480000,^GSPC
...,...,...,...,...,...,...,...,...
1250,2025-01-21,1250,6014.120117,6051.509766,6006.879883,6049.240234,4702920000,^GSPC
1251,2025-01-22,1251,6081.390137,6100.810059,6076.129883,6086.370117,4323040000,^GSPC
1252,2025-01-23,1252,6076.319824,6118.729980,6074.669922,6118.709961,4432250000,^GSPC
1253,2025-01-24,1253,6121.430176,6128.180176,6088.740234,6101.240234,4214250000,^GSPC
1254,2025-01-27,1254,5969.040039,6017.169922,5962.919922,6012.279785,5198750000,^GSPC

In [6]:
from indicators.momentum.Indicators import (
    RSI, MACD, BollingerBands, Stochastic, CCI, ATR, PPO,
    StochRSI, AO, BOP, Bias, Fisher, Brar, CG, CMO,
    Coppock, CTI, ER, Eri, Inertia, KDJ, KST, PGO,
    PVO, QQE, ROC, RSX, RVGI, Slope, SMI, Squeeze,
    SqueezePro, STC, TSI, TRIX, UO, WillR
)

In [7]:
indicators = [
    RSI, MACD, BollingerBands, Stochastic, CCI, ATR, PPO,
    # StochRSI, AO, BOP, Bias, Fisher, Brar, CG, CMO,
    # Coppock, CTI, ER, Eri, Inertia, KDJ, KST, PGO,
    # PVO, QQE, ROC, RSX, RVGI, Slope, SMI, Squeeze,
    # SqueezePro, STC, TSI, TRIX, UO, WillR
]

In [8]:
indicators

[indicators.momentum.Indicators.RSI,
 indicators.momentum.Indicators.MACD,
 indicators.momentum.Indicators.BollingerBands,
 indicators.momentum.Indicators.Stochastic,
 indicators.momentum.Indicators.CCI,
 indicators.momentum.Indicators.ATR,
 indicators.momentum.Indicators.PPO]

In [9]:
from indicators.ParamGenerator.Params import ParamGenerator

In [10]:
params_gen = ParamGenerator(data=data[:200], indicators=indicators)

In [11]:
params_gen.generate_param_ranges()

{'RSI': {'period': [1,
   2,
   3,
   4,
   5,
   6,
   7,
   8,
   9,
   10,
   11,
   12,
   13,
   14,
   15,
   16,
   17,
   18,
   19,
   20,
   21,
   22,
   23,
   24,
   25,
   26,
   27,
   28,
   29,
   30,
   31,
   32,
   33,
   34,
   35,
   36,
   37,
   38,
   39,
   40,
   41,
   42,
   43,
   44,
   45,
   46,
   47,
   48,
   49,
   50,
   51,
   52,
   53,
   54,
   55,
   56,
   57,
   58,
   59,
   60,
   61,
   62,
   63,
   64,
   65,
   66,
   67,
   68,
   69,
   70,
   71,
   72,
   73,
   74,
   75,
   76,
   77,
   78,
   79,
   80,
   81,
   82,
   83,
   84,
   85,
   86,
   87,
   88,
   89,
   90,
   91,
   92,
   93,
   94,
   95,
   96,
   97,
   98,
   99,
   100]},
 'MACD': {'short_period': [1,
   2,
   3,
   4,
   5,
   6,
   7,
   8,
   9,
   10,
   11,
   12,
   13,
   14,
   15,
   16,
   17,
   18,
   19,
   20,
   21,
   22,
   23,
   24,
   25,
   26,
   27,
   28,
   29,
   30,
   31,
   32,
   33,
   34,
   35,
   36,
   37,
   38,
   39,
   40,
   41,
   42,
   43,
   44,
   45,
   46,
   47,
   48,
   49,
   50,
   51,
   52,
   53,
   54,
   55,
   56,
   57,
   58,
   59,
   60,
   61,
   62,
   63,
   64,
   65,
   66,
   67,
   68,
   69,
   70,
   71,
   72,
   73,
   74,
   75,
   76,
   77,
   78,
   79,
   80,
   81,
   82,
   83,
   84,
   85,
   86,
   87,
   88,
   89,
   90,
   91,
   92,
   93,
   94,
   95,
   96,
   97,
   98,
   99,
   100],
  'long_period': [1,
   2,
   3,
   4,
   5,
   6,
   7,
   8,
   9,
   10,
   11,
   12,
   13,
   14,
   15,
   16,
   17,
   18,
   19,
   20,
   21,
   22,
   23,
   24,
   25,
   26,
   27,
   28,
   29,
   30,
   31,
   32,
   33,
   34,
   35,
   36,
   37,
   38,
   39,
   40,
   41,
   42,
   43,
   44,
   45,
   46,
   47,
   48,
   49,
   50,
   51,
   52,
   53,
   54,
   55,
   56,
   57,
   58,
   59,
   60,
   61,
   62,
   63,
   64,
   65,
   66,
   67,
   68,
   69,
   70,
   71,
   72,
   73,
   74,
   75,
   76,
   77,
   78,
   79,
   80,
   81,
   82,
   83,
   84,
   85,
   86,
   87,
   88,
   89,
   90,
   91,
   92,
   93,
   94,
   95,
   96,
   97,
   98,
   99,
   100],
  'signal_period': [1,
   2,
   3,
   4,
   5,
   6,
   7,
   8,
   9,
   10,
   11,
   12,
   13,
   14,
   15,
   16,
   17,
   18,
   19,
   20,
   21,
   22,
   23,
   24,
   25,
   26,
   27,
   28,
   29,
   30,
   31,
   32,
   33,
   34,
   35,
   36,
   37,
   38,
   39,
   40,
   41,
   42,
   43,
   44,
   45,
   46,
   47,
   48,
   49,
   50,
   51,
   52,
   53,
   54,
   55,
   56,
   57,
   58,
   59,
   60,
   61,
   62,
   63,
   64,
   65,
   66,
   67,
   68,
   69,
   70,
   71,
   72,
   73,
   74,
   75,
   76,
   77,
   78,
   79,
   80,
   81,
   82,
   83,
   84,
   85,
   86,
   87,
   88,
   89,
   90,
   91,
   92,
   93,
   94,
   95,
   96,
   97,
   98,
   99,
   100]},
 'BollingerBands': {'period': [1,
   2,
   3,
   4,
   5,
   6,
   7,
   8,
   9,
   10,
   11,
   12,
   13,
   14,
   15,
   16,
   17,
   18,
   19,
   20,
   21,
   22,
   23,
   24,
   25,
   26,
   27,
   28,
   29,
   30,
   31,
   32,
   33,
   34,
   35,
   36,
   37,
   38,
   39,
   40,
   41,
   42,
   43,
   44,
   45,
   46,
   47,
   48,
   49,
   50,
   51,
   52,
   53,
   54,
   55,
   56,
   57,
   58,
   59,
   60,
   61,
   62,
   63,
   64,
   65,
   66,
   67,
   68,
   69,
   70,
   71,
   72,
   73,
   74,
   75,
   76,
   77,
   78,
   79,
   80,
   81,
   82,
   83,
   84,
   85,
   86,
   87,
   88,
   89,
   90,
   91,
   92,
   93,
   94,
   95,
   96,
   97,
   98,
   99,
   100],
  'num_std': [1,
   2,
   3,
   4,
   5,
   6,
   7,
   8,
   9,
   10,
   11,
   12,
   13,
   14,
   15,
   16,
   17,
   18,
   19,
   20,
   21,
   22,
   23,
   24,
   25,
   26,
   27,
   28,
   29,
   30,
   31,
   32,
   33,
   34,
   35,
   36,
   37,
   38,
   39,
   40,
   41,
   42,
   43,
   44,
   45,
   46,
   47,
   48,
   49,
   50,
   51,
   52,
   53,
   54,
   55,
   56,
   57,
   58,
   59,
   60,
   61,
   62,
   63,
   64,
   65,
   66,
   67,
   68,
   69,
   70,
   71,
   72,
   73,
   74,
   75,
   76,
   77,
   78,
   79,
   80,
   81,
   82,
   83,
   84,
   85,
   86,
   87,
   88,
   89,
   90,
   91,
   92,
   93,
   94,
   95,
   96,
   97,
   98,
   99,
   100]},
 'Stochastic': {'period': [1,
   2,
   3,
   4,
   5,
   6,
   7,
   8,
   9,
   10,
   11,
   12,
   13,
   14,
   15,
   16,
   17,
   18,
   19,
   20,
   21,
   22,
   23,
   24,
   25,
   26,
   27,
   28,
   29,
   30,
   31,
   32,
   33,
   34,
   35,
   36,
   37,
   38,
   39,
   40,
   41,
   42,
   43,
   44,
   45,
   46,
   47,
   48,
   49,
   50,
   51,
   52,
   53,
   54,
   55,
   56,
   57,
   58,
   59,
   60,
   61,
   62,
   63,
   64,
   65,
   66,
   67,
   68,
   69,
   70,
   71,
   72,
   73,
   74,
   75,
   76,
   77,
   78,
   79,
   80,
   81,
   82,
   83,
   84,
   85,
   86,
   87,
   88,
   89,
   90,
   91,
   92,
   93,
   94,
   95,
   96,
   97,
   98,
   99,
   100]},
 'CCI': {'period': [1,
   2,
   3,
   4,
   5,
   6,
   7,
   8,
   9,
   10,
   11,
   12,
   13,
   14,
   15,
   16,
   17,
   18,
   19,
   20,
   21,
   22,
   23,
   24,
   25,
   26,
   27,
   28,
   29,
   30,
   31,
   32,
   33,
   34,
   35,
   36,
   37,
   38,
   39,
   40,
   41,
   42,
   43,
   44,
   45,
   46,
   47,
   48,
   49,
   50,
   51,
   52,
   53,
   54,
   55,
   56,
   57,
   58,
   59,
   60,
   61,
   62,
   63,
   64,
   65,
   66,
   67,
   68,
   69,
   70,
   71,
   72,
   73,
   74,
   75,
   76,
   77,
   78,
   79,
   80,
   81,
   82,
   83,
   84,
   85,
   86,
   87,
   88,
   89,
   90,
   91,
   92,
   93,
   94,
   95,
   96,
   97,
   98,
   99,
   100]},
 'ATR': {'period': [1,
   2,
   3,
   4,
   5,
   6,
   7,
   8,
   9,
   10,
   11,
   12,
   13,
   14,
   15,
   16,
   17,
   18,
   19,
   20,
   21,
   22,
   23,
   24,
   25,
   26,
   27,
   28,
   29,
   30,
   31,
   32,
   33,
   34,
   35,
   36,
   37,
   38,
   39,
   40,
   41,
   42,
   43,
   44,
   45,
   46,
   47,
   48,
   49,
   50,
   51,
   52,
   53,
   54,
   55,
   56,
   57,
   58,
   59,
   60,
   61,
   62,
   63,
   64,
   65,
   66,
   67,
   68,
   69,
   70,
   71,
   72,
   73,
   74,
   75,
   76,
   77,
   78,
   79,
   80,
   81,
   82,
   83,
   84,
   85,
   86,
   87,
   88,
   89,
   90,
   91,
   92,
   93,
   94,
   95,
   96,
   97,
   98,
   99,
   100]},
 'PPO': {'fast_period': [1,
   2,
   3,
   4,
   5,
   6,
   7,
   8,
   9,
   10,
   11,
   12,
   13,
   14,
   15,
   16,
   17,
   18,
   19,
   20,
   21,
   22,
   23,
   24,
   25,
   26,
   27,
   28,
   29,
   30,
   31,
   32,
   33,
   34,
   35,
   36,
   37,
   38,
   39,
   40,
   41,
   42,
   43,
   44,
   45,
   46,
   47,
   48,
   49,
   50,
   51,
   52,
   53,
   54,
   55,
   56,
   57,
   58,
   59,
   60,
   61,
   62,
   63,
   64,
   65,
   66,
   67,
   68,
   69,
   70,
   71,
   72,
   73,
   74,
   75,
   76,
   77,
   78,
   79,
   80,
   81,
   82,
   83,
   84,
   85,
   86,
   87,
   88,
   89,
   90,
   91,
   92,
   93,
   94,
   95,
   96,
   97,
   98,
   99,
   100],
  'sLow_period': [1,
   2,
   3,
   4,
   5,
   6,
   7,
   8,
   9,
   10,
   11,
   12,
   13,
   14,
   15,
   16,
   17,
   18,
   19,
   20,
   21,
   22,
   23,
   24,
   25,
   26,
   27,
   28,
   29,
   30,
   31,
   32,
   33,
   34,
   35,
   36,
   37,
   38,
   39,
   40,
   41,
   42,
   43,
   44,
   45,
   46,
   47,
   48,
   49,
   50,
   51,
   52,
   53,
   54,
   55,
   56,
   57,
   58,
   59,
   60,
   61,
   62,
   63,
   64,
   65,
   66,
   67,
   68,
   69,
   70,
   71,
   72,
   73,
   74,
   75,
   76,
   77,
   78,
   79,
   80,
   81,
   82,
   83,
   84,
   85,
   86,
   87,
   88,
   89,
   90,
   91,
   92,
   93,
   94,
   95,
   96,
   97,
   98,
   99,
   100]}}

In [12]:
params_gen.generate_unique_combinations(params_gen.generate_param_ranges())

{'RSI': [{'period': 1},
  {'period': 2},
  {'period': 3},
  {'period': 4},
  {'period': 5},
  {'period': 6},
  {'period': 7},
  {'period': 8},
  {'period': 9},
  {'period': 10},
  {'period': 11},
  {'period': 12},
  {'period': 13},
  {'period': 14},
  {'period': 15},
  {'period': 16},
  {'period': 17},
  {'period': 18},
  {'period': 19},
  {'period': 20},
  {'period': 21},
  {'period': 22},
  {'period': 23},
  {'period': 24},
  {'period': 25},
  {'period': 26},
  {'period': 27},
  {'period': 28},
  {'period': 29},
  {'period': 30},
  {'period': 31},
  {'period': 32},
  {'period': 33},
  {'period': 34},
  {'period': 35},
  {'period': 36},
  {'period': 37},
  {'period': 38},
  {'period': 39},
  {'period': 40},
  {'period': 41},
  {'period': 42},
  {'period': 43},
  {'period': 44},
  {'period': 45},
  {'period': 46},
  {'period': 47},
  {'period': 48},
  {'period': 49},
  {'period': 50},
  {'period': 51},
  {'period': 52},
  {'period': 53},
  {'period': 54},
  {'period': 55},
  {'period': 56},
  {'period': 57},
  {'period': 58},
  {'period': 59},
  {'period': 60},
  {'period': 61},
  {'period': 62},
  {'period': 63},
  {'period': 64},
  {'period': 65},
  {'period': 66},
  {'period': 67},
  {'period': 68},
  {'period': 69},
  {'period': 70},
  {'period': 71},
  {'period': 72},
  {'period': 73},
  {'period': 74},
  {'period': 75},
  {'period': 76},
  {'period': 77},
  {'period': 78},
  {'period': 79},
  {'period': 80},
  {'period': 81},
  {'period': 82},
  {'period': 83},
  {'period': 84},
  {'period': 85},
  {'period': 86},
  {'period': 87},
  {'period': 88},
  {'period': 89},
  {'period': 90},
  {'period': 91},
  {'period': 92},
  {'period': 93},
  {'period': 94},
  {'period': 95},
  {'period': 96},
  {'period': 97},
  {'period': 98},
  {'period': 99},
  {'period': 100}],
 'MACD': [{'short_period': 1, 'long_period': 1, 'signal_period': 1},
  {'short_period': 1, 'long_period': 1, 'signal_period': 2},
  {'short_period': 1, 'long_period': 1, 'signal_period': 3},
  {'short_period': 1, 'long_period': 1, 'signal_period': 4},
  {'short_period': 1, 'long_period': 1, 'signal_period': 5},
  {'short_period': 1, 'long_period': 1, 'signal_period': 6},
  {'short_period': 1, 'long_period': 1, 'signal_period': 7},
  {'short_period': 1, 'long_period': 1, 'signal_period': 8},
  {'short_period': 1, 'long_period': 1, 'signal_period': 9},
  {'short_period': 1, 'long_period': 1, 'signal_period': 10},
  {'short_period': 1, 'long_period': 1, 'signal_period': 11},
  {'short_period': 1, 'long_period': 1, 'signal_period': 12},
  {'short_period': 1, 'long_period': 1, 'signal_period': 13},
  {'short_period': 1, 'long_period': 1, 'signal_period': 14},
  {'short_period': 1, 'long_period': 1, 'signal_period': 15},
  {'short_period': 1, 'long_period': 1, 'signal_period': 16},
  {'short_period': 1, 'long_period': 1, 'signal_period': 17},
  {'short_period': 1, 'long_period': 1, 'signal_period': 18},
  {'short_period': 1, 'long_period': 1, 'signal_period': 19},
  {'short_period': 1, 'long_period': 1, 'signal_period': 20},
  {'short_period': 1, 'long_period': 1, 'signal_period': 21},
  {'short_period': 1, 'long_period': 1, 'signal_period': 22},
  {'short_period': 1, 'long_period': 1, 'signal_period': 23},
  {'short_period': 1, 'long_period': 1, 'signal_period': 24},
  {'short_period': 1, 'long_period': 1, 'signal_period': 25},
  {'short_period': 1, 'long_period': 1, 'signal_period': 26},
  {'short_period': 1, 'long_period': 1, 'signal_period': 27},
  {'short_period': 1, 'long_period': 1, 'signal_period': 28},
  {'short_period': 1, 'long_period': 1, 'signal_period': 29},
  {'short_period': 1, 'long_period': 1, 'signal_period': 30},
  {'short_period': 1, 'long_period': 1, 'signal_period': 31},
  {'short_period': 1, 'long_period': 1, 'signal_period': 32},
  {'short_period': 1, 'long_period': 1, 'signal_period': 33},
  {'short_period': 1, 'long_period': 1, 'signal_period': 34},
  {'short_period': 1, 'long_period': 1, 'signal_period': 35},
  {'short_period': 1, 'long_period': 1, 'signal_period': 36},
  {'short_period': 1, 'long_period': 1, 'signal_period': 37},
  {'short_period': 1, 'long_period': 1, 'signal_period': 38},
  {'short_period': 1, 'long_period': 1, 'signal_period': 39},
  {'short_period': 1, 'long_period': 1, 'signal_period': 40},
  {'short_period': 1, 'long_period': 1, 'signal_period': 41},
  {'short_period': 1, 'long_period': 1, 'signal_period': 42},
  {'short_period': 1, 'long_period': 1, 'signal_period': 43},
  {'short_period': 1, 'long_period': 1, 'signal_period': 44},
  {'short_period': 1, 'long_period': 1, 'signal_period': 45},
  {'short_period': 1, 'long_period': 1, 'signal_period': 46},
  {'short_period': 1, 'long_period': 1, 'signal_period': 47},
  {'short_period': 1, 'long_period': 1, 'signal_period': 48},
  {'short_period': 1, 'long_period': 1, 'signal_period': 49},
  {'short_period': 1, 'long_period': 1, 'signal_period': 50},
  {'short_period': 1, 'long_period': 1, 'signal_period': 51},
  {'short_period': 1, 'long_period': 1, 'signal_period': 52},
  {'short_period': 1, 'long_period': 1, 'signal_period': 53},
  {'short_period': 1, 'long_period': 1, 'signal_period': 54},
  {'short_period': 1, 'long_period': 1, 'signal_period': 55},
  {'short_period': 1, 'long_period': 1, 'signal_period': 56},
  {'short_period': 1, 'long_period': 1, 'signal_period': 57},
  {'short_period': 1, 'long_period': 1, 'signal_period': 58},
  {'short_period': 1, 'long_period': 1, 'signal_period': 59},
  {'short_period': 1, 'long_period': 1, 'signal_period': 60},
  {'short_period': 1, 'long_period': 1, 'signal_period': 61},
  {'short_period': 1, 'long_period': 1, 'signal_period': 62},
  {'short_period': 1, 'long_period': 1, 'signal_period': 63},
  {'short_period': 1, 'long_period': 1, 'signal_period': 64},
  {'short_period': 1, 'long_period': 1, 'signal_period': 65},
  {'short_period': 1, 'long_period': 1, 'signal_period': 66},
  {'short_period': 1, 'long_period': 1, 'signal_period': 67},
  {'short_period': 1, 'long_period': 1, 'signal_period': 68},
  {'short_period': 1, 'long_period': 1, 'signal_period': 69},
  {'short_period': 1, 'long_period': 1, 'signal_period': 70},
  {'short_period': 1, 'long_period': 1, 'signal_period': 71},
  {'short_period': 1, 'long_period': 1, 'signal_period': 72},
  {'short_period': 1, 'long_period': 1, 'signal_period': 73},
  {'short_period': 1, 'long_period': 1, 'signal_period': 74},
  {'short_period': 1, 'long_period': 1, 'signal_period': 75},
  {'short_period': 1, 'long_period': 1, 'signal_period': 76},
  {'short_period': 1, 'long_period': 1, 'signal_period': 77},
  {'short_period': 1, 'long_period': 1, 'signal_period': 78},
  {'short_period': 1, 'long_period': 1, 'signal_period': 79},
  {'short_period': 1, 'long_period': 1, 'signal_period': 80},
  {'short_period': 1, 'long_period': 1, 'signal_period': 81},
  {'short_period': 1, 'long_period': 1, 'signal_period': 82},
  {'short_period': 1, 'long_period': 1, 'signal_period': 83},
  {'short_period': 1, 'long_period': 1, 'signal_period': 84},
  {'short_period': 1, 'long_period': 1, 'signal_period': 85},
  {'short_period': 1, 'long_period': 1, 'signal_period': 86},
  {'short_period': 1, 'long_period': 1, 'signal_period': 87},
  {'short_period': 1, 'long_period': 1, 'signal_period': 88},
  {'short_period': 1, 'long_period': 1, 'signal_period': 89},
  {'short_period': 1, 'long_period': 1, 'signal_period': 90},
  {'short_period': 1, 'long_period': 1, 'signal_period': 91},
  {'short_period': 1, 'long_period': 1, 'signal_period': 92},
  {'short_period': 1, 'long_period': 1, 'signal_period': 93},
  {'short_period': 1, 'long_period': 1, 'signal_period': 94},
  {'short_period': 1, 'long_period': 1, 'signal_period': 95},
  {'short_period': 1, 'long_period': 1, 'signal_period': 96},
  {'short_period': 1, 'long_period': 1, 'signal_period': 97},
  {'short_period': 1, 'long_period': 1, 'signal_period': 98},
  {'short_period': 1, 'long_period': 1, 'signal_period': 99},
  {'short_period': 1, 'long_period': 1, 'signal_period': 100},
  {'short_period': 1, 'long_period': 2, 'signal_period': 1},
  {'short_period': 1, 'long_period': 2, 'signal_period': 2},
  {'short_period': 1, 'long_period': 2, 'signal_period': 3},
  {'short_period': 1, 'long_period': 2, 'signal_period': 4},
  {'short_period': 1, 'long_period': 2, 'signal_period': 5},
  {'short_period': 1, 'long_period': 2, 'signal_period': 6},
  {'short_period': 1, 'long_period': 2, 'signal_period': 7},
  {'short_period': 1, 'long_period': 2, 'signal_period': 8},
  {'short_period': 1, 'long_period': 2, 'signal_period': 9},
  {'short_period': 1, 'long_period': 2, 'signal_period': 10},
  {'short_period': 1, 'long_period': 2, 'signal_period': 11},
  {'short_period': 1, 'long_period': 2, 'signal_period': 12},
  {'short_period': 1, 'long_period': 2, 'signal_period': 13},
  {'short_period': 1, 'long_period': 2, 'signal_period': 14},
  {'short_period': 1, 'long_period': 2, 'signal_period': 15},
  {'short_period': 1, 'long_period': 2, 'signal_period': 16},
  {'short_period': 1, 'long_period': 2, 'signal_period': 17},
  {'short_period': 1, 'long_period': 2, 'signal_period': 18},
  {'short_period': 1, 'long_period': 2, 'signal_period': 19},
  {'short_period': 1, 'long_period': 2, 'signal_period': 20},
  {'short_period': 1, 'long_period': 2, 'signal_period': 21},
  {'short_period': 1, 'long_period': 2, 'signal_period': 22},
  {'short_period': 1, 'long_period': 2, 'signal_period': 23},
  {'short_period': 1, 'long_period': 2, 'signal_period': 24},
  {'short_period': 1, 'long_period': 2, 'signal_period': 25},
  {'short_period': 1, 'long_period': 2, 'signal_period': 26},
  {'short_period': 1, 'long_period': 2, 'signal_period': 27},
  {'short_period': 1, 'long_period': 2, 'signal_period': 28},
  {'short_period': 1, 'long_period': 2, 'signal_period': 29},
  {'short_period': 1, 'long_period': 2, 'signal_period': 30},
  {'short_period': 1, 'long_period': 2, 'signal_period': 31},
  {'short_period': 1, 'long_period': 2, 'signal_period': 32},
  {'short_period': 1, 'long_period': 2, 'signal_period': 33},
  {'short_period': 1, 'long_period': 2, 'signal_period': 34},
  {'short_period': 1, 'long_period': 2, 'signal_period': 35},
  {'short_period': 1, 'long_period': 2, 'signal_period': 36},
  {'short_period': 1, 'long_period': 2, 'signal_period': 37},
  {'short_period': 1, 'long_period': 2, 'signal_period': 38},
  {'short_period': 1, 'long_period': 2, 'signal_period': 39},
  {'short_period': 1, 'long_period': 2, 'signal_period': 40},
  {'short_period': 1, 'long_period': 2, 'signal_period': 41},
  {'short_period': 1, 'long_period': 2, 'signal_period': 42},
  {'short_period': 1, 'long_period': 2, 'signal_period': 43},
  {'short_period': 1, 'long_period': 2, 'signal_period': 44},
  {'short_period': 1, 'long_period': 2, 'signal_period': 45},
  {'short_period': 1, 'long_period': 2, 'signal_period': 46},
  {'short_period': 1, 'long_period': 2, 'signal_period': 47},
  {'short_period': 1, 'long_period': 2, 'signal_period': 48},
  {'short_period': 1, 'long_period': 2, 'signal_period': 49},
  {'short_period': 1, 'long_period': 2, 'signal_period': 50},
  {'short_period': 1, 'long_period': 2, 'signal_period': 51},
  {'short_period': 1, 'long_period': 2, 'signal_period': 52},
  {'short_period': 1, 'long_period': 2, 'signal_period': 53},
  {'short_period': 1, 'long_period': 2, 'signal_period': 54},
  {'short_period': 1, 'long_period': 2, 'signal_period': 55},
  {'short_period': 1, 'long_period': 2, 'signal_period': 56},
  {'short_period': 1, 'long_period': 2, 'signal_period': 57},
  {'short_period': 1, 'long_period': 2, 'signal_period': 58},
  {'short_period': 1, 'long_period': 2, 'signal_period': 59},
  {'short_period': 1, 'long_period': 2, 'signal_period': 60},
  {'short_period': 1, 'long_period': 2, 'signal_period': 61},
  {'short_period': 1, 'long_period': 2, 'signal_period': 62},
  {'short_period': 1, 'long_period': 2, 'signal_period': 63},
  {'short_period': 1, 'long_period': 2, 'signal_period': 64},
  {'short_period': 1, 'long_period': 2, 'signal_period': 65},
  {'short_period': 1, 'long_period': 2, 'signal_period': 66},
  {'short_period': 1, 'long_period': 2, 'signal_period': 67},
  {'short_period': 1, 'long_period': 2, 'signal_period': 68},
  {'short_period': 1, 'long_period': 2, 'signal_period': 69},
  {'short_period': 1, 'long_period': 2, 'signal_period': 70},
  {'short_period': 1, 'long_period': 2, 'signal_period': 71},
  {'short_period': 1, 'long_period': 2, 'signal_period': 72},
  {'short_period': 1, 'long_period': 2, 'signal_period': 73},
  {'short_period': 1, 'long_period': 2, 'signal_period': 74},
  {'short_period': 1, 'long_period': 2, 'signal_period': 75},
  {'short_period': 1, 'long_period': 2, 'signal_period': 76},
  {'short_period': 1, 'long_period': 2, 'signal_period': 77},
  {'short_period': 1, 'long_period': 2, 'signal_period': 78},
  {'short_period': 1, 'long_period': 2, 'signal_period': 79},
  {'short_period': 1, 'long_period': 2, 'signal_period': 80},
  {'short_period': 1, 'long_period': 2, 'signal_period': 81},
  {'short_period': 1, 'long_period': 2, 'signal_period': 82},
  {'short_period': 1, 'long_period': 2, 'signal_period': 83},
  {'short_period': 1, 'long_period': 2, 'signal_period': 84},
  {'short_period': 1, 'long_period': 2, 'signal_period': 85},
  {'short_period': 1, 'long_period': 2, 'signal_period': 86},
  {'short_period': 1, 'long_period': 2, 'signal_period': 87},
  {'short_period': 1, 'long_period': 2, 'signal_period': 88},
  {'short_period': 1, 'long_period': 2, 'signal_period': 89},
  {'short_period': 1, 'long_period': 2, 'signal_period': 90},
  {'short_period': 1, 'long_period': 2, 'signal_period': 91},
  {'short_period': 1, 'long_period': 2, 'signal_period': 92},
  {'short_period': 1, 'long_period': 2, 'signal_period': 93},
  {'short_period': 1, 'long_period': 2, 'signal_period': 94},
  {'short_period': 1, 'long_period': 2, 'signal_period': 95},
  {'short_period': 1, 'long_period': 2, 'signal_period': 96},
  {'short_period': 1, 'long_period': 2, 'signal_period': 97},
  {'short_period': 1, 'long_period': 2, 'signal_period': 98},
  {'short_period': 1, 'long_period': 2, 'signal_period': 99},
  {'short_period': 1, 'long_period': 2, 'signal_period': 100},
  {'short_period': 1, 'long_period': 3, 'signal_period': 1},
  {'short_period': 1, 'long_period': 3, 'signal_period': 2},
  {'short_period': 1, 'long_period': 3, 'signal_period': 3},
  {'short_period': 1, 'long_period': 3, 'signal_period': 4},
  {'short_period': 1, 'long_period': 3, 'signal_period': 5},
  {'short_period': 1, 'long_period': 3, 'signal_period': 6},
  {'short_period': 1, 'long_period': 3, 'signal_period': 7},
  {'short_period': 1, 'long_period': 3, 'signal_period': 8},
  {'short_period': 1, 'long_period': 3, 'signal_period': 9},
  {'short_period': 1, 'long_period': 3, 'signal_period': 10},
  {'short_period': 1, 'long_period': 3, 'signal_period': 11},
  {'short_period': 1, 'long_period': 3, 'signal_period': 12},
  {'short_period': 1, 'long_period': 3, 'signal_period': 13},
  {'short_period': 1, 'long_period': 3, 'signal_period': 14},
  {'short_period': 1, 'long_period': 3, 'signal_period': 15},
  {'short_period': 1, 'long_period': 3, 'signal_period': 16},
  {'short_period': 1, 'long_period': 3, 'signal_period': 17},
  {'short_period': 1, 'long_period': 3, 'signal_period': 18},
  {'short_period': 1, 'long_period': 3, 'signal_period': 19},
  {'short_period': 1, 'long_period': 3, 'signal_period': 20},
  {'short_period': 1, 'long_period': 3, 'signal_period': 21},
  {'short_period': 1, 'long_period': 3, 'signal_period': 22},
  {'short_period': 1, 'long_period': 3, 'signal_period': 23},
  {'short_period': 1, 'long_period': 3, 'signal_period': 24},
  {'short_period': 1, 'long_period': 3, 'signal_period': 25},
  {'short_period': 1, 'long_period': 3, 'signal_period': 26},
  {'short_period': 1, 'long_period': 3, 'signal_period': 27},
  {'short_period': 1, 'long_period': 3, 'signal_period': 28},
  {'short_period': 1, 'long_period': 3, 'signal_period': 29},
  {'short_period': 1, 'long_period': 3, 'signal_period': 30},
  {'short_period': 1, 'long_period': 3, 'signal_period': 31},
  {'short_period': 1, 'long_period': 3, 'signal_period': 32},
  {'short_period': 1, 'long_period': 3, 'signal_period': 33},
  {'short_period': 1, 'long_period': 3, 'signal_period': 34},
  {'short_period': 1, 'long_period': 3, 'signal_period': 35},
  {'short_period': 1, 'long_period': 3, 'signal_period': 36},
  {'short_period': 1, 'long_period': 3, 'signal_period': 37},
  {'short_period': 1, 'long_period': 3, 'signal_period': 38},
  {'short_period': 1, 'long_period': 3, 'signal_period': 39},
  {'short_period': 1, 'long_period': 3, 'signal_period': 40},
  {'short_period': 1, 'long_period': 3, 'signal_period': 41},
  {'short_period': 1, 'long_period': 3, 'signal_period': 42},
  {'short_period': 1, 'long_period': 3, 'signal_period': 43},
  {'short_period': 1, 'long_period': 3, 'signal_period': 44},
  {'short_period': 1, 'long_period': 3, 'signal_period': 45},
  {'short_period': 1, 'long_period': 3, 'signal_period': 46},
  {'short_period': 1, 'long_period': 3, 'signal_period': 47},
  {'short_period': 1, 'long_period': 3, 'signal_period': 48},
  {'short_period': 1, 'long_period': 3, 'signal_period': 49},
  {'short_period': 1, 'long_period': 3, 'signal_period': 50},
  {'short_period': 1, 'long_period': 3, 'signal_period': 51},
  {'short_period': 1, 'long_period': 3, 'signal_period': 52},
  {'short_period': 1, 'long_period': 3, 'signal_period': 53},
  {'short_period': 1, 'long_period': 3, 'signal_period': 54},
  {'short_period': 1, 'long_period': 3, 'signal_period': 55},
  {'short_period': 1, 'long_period': 3, 'signal_period': 56},
  {'short_period': 1, 'long_period': 3, 'signal_period': 57},
  {'short_period': 1, 'long_period': 3, 'signal_period': 58},
  {'short_period': 1, 'long_period': 3, 'signal_period': 59},
  {'short_period': 1, 'long_period': 3, 'signal_period': 60},
  {'short_period': 1, 'long_period': 3, 'signal_period': 61},
  {'short_period': 1, 'long_period': 3, 'signal_period': 62},
  {'short_period': 1, 'long_period': 3, 'signal_period': 63},
  {'short_period': 1, 'long_period': 3, 'signal_period': 64},
  {'short_period': 1, 'long_period': 3, 'signal_period': 65},
  {'short_period': 1, 'long_period': 3, 'signal_period': 66},
  {'short_period': 1, 'long_period': 3, 'signal_period': 67},
  {'short_period': 1, 'long_period': 3, 'signal_period': 68},
  {'short_period': 1, 'long_period': 3, 'signal_period': 69},
  {'short_period': 1, 'long_period': 3, 'signal_period': 70},
  {'short_period': 1, 'long_period': 3, 'signal_period': 71},
  {'short_period': 1, 'long_period': 3, 'signal_period': 72},
  {'short_period': 1, 'long_period': 3, 'signal_period': 73},
  {'short_period': 1, 'long_period': 3, 'signal_period': 74},
  {'short_period': 1, 'long_period': 3, 'signal_period': 75},
  {'short_period': 1, 'long_period': 3, 'signal_period': 76},
  {'short_period': 1, 'long_period': 3, 'signal_period': 77},
  {'short_period': 1, 'long_period': 3, 'signal_period': 78},
  {'short_period': 1, 'long_period': 3, 'signal_period': 79},
  {'short_period': 1, 'long_period': 3, 'signal_period': 80},
  {'short_period': 1, 'long_period': 3, 'signal_period': 81},
  {'short_period': 1, 'long_period': 3, 'signal_period': 82},
  {'short_period': 1, 'long_period': 3, 'signal_period': 83},
  {'short_period': 1, 'long_period': 3, 'signal_period': 84},
  {'short_period': 1, 'long_period': 3, 'signal_period': 85},
  {'short_period': 1, 'long_period': 3, 'signal_period': 86},
  {'short_period': 1, 'long_period': 3, 'signal_period': 87},
  {'short_period': 1, 'long_period': 3, 'signal_period': 88},
  {'short_period': 1, 'long_period': 3, 'signal_period': 89},
  {'short_period': 1, 'long_period': 3, 'signal_period': 90},
  {'short_period': 1, 'long_period': 3, 'signal_period': 91},
  {'short_period': 1, 'long_period': 3, 'signal_period': 92},
  {'short_period': 1, 'long_period': 3, 'signal_period': 93},

In [13]:
param_ranges, unique_combinations, df = params_gen.params_data_calculator()

In [14]:
param_ranges

{'RSI': {'period': [1,
   2,
   3,
   4,
   5,
   6,
   7,
   8,
   9,
   10,
   11,
   12,
   13,
   14,
   15,
   16,
   17,
   18,
   19,
   20,
   21,
   22,
   23,
   24,
   25,
   26,
   27,
   28,
   29,
   30,
   31,
   32,
   33,
   34,
   35,
   36,
   37,
   38,
   39,
   40,
   41,
   42,
   43,
   44,
   45,
   46,
   47,
   48,
   49,
   50,
   51,
   52,
   53,
   54,
   55,
   56,
   57,
   58,
   59,
   60,
   61,
   62,
   63,
   64,
   65,
   66,
   67,
   68,
   69,
   70,
   71,
   72,
   73,
   74,
   75,
   76,
   77,
   78,
   79,
   80,
   81,
   82,
   83,
   84,
   85,
   86,
   87,
   88,
   89,
   90,
   91,
   92,
   93,
   94,
   95,
   96,
   97,
   98,
   99,
   100]},
 'MACD': {'short_period': [1,
   2,
   3,
   4,
   5,
   6,
   7,
   8,
   9,
   10,
   11,
   12,
   13,
   14,
   15,
   16,
   17,
   18,
   19,
   20,
   21,
   22,
   23,
   24,
   25,
   26,
   27,
   28,
   29,
   30,
   31,
   32,
   33,
   34,
   35,
   36,
   37,
   38,
   39,
   40,
   41,
   42,
   43,
   44,
   45,
   46,
   47,
   48,
   49,
   50,
   51,
   52,
   53,
   54,
   55,
   56,
   57,
   58,
   59,
   60,
   61,
   62,
   63,
   64,
   65,
   66,
   67,
   68,
   69,
   70,
   71,
   72,
   73,
   74,
   75,
   76,
   77,
   78,
   79,
   80,
   81,
   82,
   83,
   84,
   85,
   86,
   87,
   88,
   89,
   90,
   91,
   92,
   93,
   94,
   95,
   96,
   97,
   98,
   99,
   100],
  'long_period': [1,
   2,
   3,
   4,
   5,
   6,
   7,
   8,
   9,
   10,
   11,
   12,
   13,
   14,
   15,
   16,
   17,
   18,
   19,
   20,
   21,
   22,
   23,
   24,
   25,
   26,
   27,
   28,
   29,
   30,
   31,
   32,
   33,
   34,
   35,
   36,
   37,
   38,
   39,
   40,
   41,
   42,
   43,
   44,
   45,
   46,
   47,
   48,
   49,
   50,
   51,
   52,
   53,
   54,
   55,
   56,
   57,
   58,
   59,
   60,
   61,
   62,
   63,
   64,
   65,
   66,
   67,
   68,
   69,
   70,
   71,
   72,
   73,
   74,
   75,
   76,
   77,
   78,
   79,
   80,
   81,
   82,
   83,
   84,
   85,
   86,
   87,
   88,
   89,
   90,
   91,
   92,
   93,
   94,
   95,
   96,
   97,
   98,
   99,
   100],
  'signal_period': [1,
   2,
   3,
   4,
   5,
   6,
   7,
   8,
   9,
   10,
   11,
   12,
   13,
   14,
   15,
   16,
   17,
   18,
   19,
   20,
   21,
   22,
   23,
   24,
   25,
   26,
   27,
   28,
   29,
   30,
   31,
   32,
   33,
   34,
   35,
   36,
   37,
   38,
   39,
   40,
   41,
   42,
   43,
   44,
   45,
   46,
   47,
   48,
   49,
   50,
   51,
   52,
   53,
   54,
   55,
   56,
   57,
   58,
   59,
   60,
   61,
   62,
   63,
   64,
   65,
   66,
   67,
   68,
   69,
   70,
   71,
   72,
   73,
   74,
   75,
   76,
   77,
   78,
   79,
   80,
   81,
   82,
   83,
   84,
   85,
   86,
   87,
   88,
   89,
   90,
   91,
   92,
   93,
   94,
   95,
   96,
   97,
   98,
   99,
   100]},
 'BollingerBands': {'period': [1,
   2,
   3,
   4,
   5,
   6,
   7,
   8,
   9,
   10,
   11,
   12,
   13,
   14,
   15,
   16,
   17,
   18,
   19,
   20,
   21,
   22,
   23,
   24,
   25,
   26,
   27,
   28,
   29,
   30,
   31,
   32,
   33,
   34,
   35,
   36,
   37,
   38,
   39,
   40,
   41,
   42,
   43,
   44,
   45,
   46,
   47,
   48,
   49,
   50,
   51,
   52,
   53,
   54,
   55,
   56,
   57,
   58,
   59,
   60,
   61,
   62,
   63,
   64,
   65,
   66,
   67,
   68,
   69,
   70,
   71,
   72,
   73,
   74,
   75,
   76,
   77,
   78,
   79,
   80,
   81,
   82,
   83,
   84,
   85,
   86,
   87,
   88,
   89,
   90,
   91,
   92,
   93,
   94,
   95,
   96,
   97,
   98,
   99,
   100],
  'num_std': [1,
   2,
   3,
   4,
   5,
   6,
   7,
   8,
   9,
   10,
   11,
   12,
   13,
   14,
   15,
   16,
   17,
   18,
   19,
   20,
   21,
   22,
   23,
   24,
   25,
   26,
   27,
   28,
   29,
   30,
   31,
   32,
   33,
   34,
   35,
   36,
   37,
   38,
   39,
   40,
   41,
   42,
   43,
   44,
   45,
   46,
   47,
   48,
   49,
   50,
   51,
   52,
   53,
   54,
   55,
   56,
   57,
   58,
   59,
   60,
   61,
   62,
   63,
   64,
   65,
   66,
   67,
   68,
   69,
   70,
   71,
   72,
   73,
   74,
   75,
   76,
   77,
   78,
   79,
   80,
   81,
   82,
   83,
   84,
   85,
   86,
   87,
   88,
   89,
   90,
   91,
   92,
   93,
   94,
   95,
   96,
   97,
   98,
   99,
   100]},
 'Stochastic': {'period': [1,
   2,
   3,
   4,
   5,
   6,
   7,
   8,
   9,
   10,
   11,
   12,
   13,
   14,
   15,
   16,
   17,
   18,
   19,
   20,
   21,
   22,
   23,
   24,
   25,
   26,
   27,
   28,
   29,
   30,
   31,
   32,
   33,
   34,
   35,
   36,
   37,
   38,
   39,
   40,
   41,
   42,
   43,
   44,
   45,
   46,
   47,
   48,
   49,
   50,
   51,
   52,
   53,
   54,
   55,
   56,
   57,
   58,
   59,
   60,
   61,
   62,
   63,
   64,
   65,
   66,
   67,
   68,
   69,
   70,
   71,
   72,
   73,
   74,
   75,
   76,
   77,
   78,
   79,
   80,
   81,
   82,
   83,
   84,
   85,
   86,
   87,
   88,
   89,
   90,
   91,
   92,
   93,
   94,
   95,
   96,
   97,
   98,
   99,
   100]},
 'CCI': {'period': [1,
   2,
   3,
   4,
   5,
   6,
   7,
   8,
   9,
   10,
   11,
   12,
   13,
   14,
   15,
   16,
   17,
   18,
   19,
   20,
   21,
   22,
   23,
   24,
   25,
   26,
   27,
   28,
   29,
   30,
   31,
   32,
   33,
   34,
   35,
   36,
   37,
   38,
   39,
   40,
   41,
   42,
   43,
   44,
   45,
   46,
   47,
   48,
   49,
   50,
   51,
   52,
   53,
   54,
   55,
   56,
   57,
   58,
   59,
   60,
   61,
   62,
   63,
   64,
   65,
   66,
   67,
   68,
   69,
   70,
   71,
   72,
   73,
   74,
   75,
   76,
   77,
   78,
   79,
   80,
   81,
   82,
   83,
   84,
   85,
   86,
   87,
   88,
   89,
   90,
   91,
   92,
   93,
   94,
   95,
   96,
   97,
   98,
   99,
   100]},
 'ATR': {'period': [1,
   2,
   3,
   4,
   5,
   6,
   7,
   8,
   9,
   10,
   11,
   12,
   13,
   14,
   15,
   16,
   17,
   18,
   19,
   20,
   21,
   22,
   23,
   24,
   25,
   26,
   27,
   28,
   29,
   30,
   31,
   32,
   33,
   34,
   35,
   36,
   37,
   38,
   39,
   40,
   41,
   42,
   43,
   44,
   45,
   46,
   47,
   48,
   49,
   50,
   51,
   52,
   53,
   54,
   55,
   56,
   57,
   58,
   59,
   60,
   61,
   62,
   63,
   64,
   65,
   66,
   67,
   68,
   69,
   70,
   71,
   72,
   73,
   74,
   75,
   76,
   77,
   78,
   79,
   80,
   81,
   82,
   83,
   84,
   85,
   86,
   87,
   88,
   89,
   90,
   91,
   92,
   93,
   94,
   95,
   96,
   97,
   98,
   99,
   100]},
 'PPO': {'fast_period': [1,
   2,
   3,
   4,
   5,
   6,
   7,
   8,
   9,
   10,
   11,
   12,
   13,
   14,
   15,
   16,
   17,
   18,
   19,
   20,
   21,
   22,
   23,
   24,
   25,
   26,
   27,
   28,
   29,
   30,
   31,
   32,
   33,
   34,
   35,
   36,
   37,
   38,
   39,
   40,
   41,
   42,
   43,
   44,
   45,
   46,
   47,
   48,
   49,
   50,
   51,
   52,
   53,
   54,
   55,
   56,
   57,
   58,
   59,
   60,
   61,
   62,
   63,
   64,
   65,
   66,
   67,
   68,
   69,
   70,
   71,
   72,
   73,
   74,
   75,
   76,
   77,
   78,
   79,
   80,
   81,
   82,
   83,
   84,
   85,
   86,
   87,
   88,
   89,
   90,
   91,
   92,
   93,
   94,
   95,
   96,
   97,
   98,
   99,
   100],
  'sLow_period': [1,
   2,
   3,
   4,
   5,
   6,
   7,
   8,
   9,
   10,
   11,
   12,
   13,
   14,
   15,
   16,
   17,
   18,
   19,
   20,
   21,
   22,
   23,
   24,
   25,
   26,
   27,
   28,
   29,
   30,
   31,
   32,
   33,
   34,
   35,
   36,
   37,
   38,
   39,
   40,
   41,
   42,
   43,
   44,
   45,
   46,
   47,
   48,
   49,
   50,
   51,
   52,
   53,
   54,
   55,
   56,
   57,
   58,
   59,
   60,
   61,
   62,
   63,
   64,
   65,
   66,
   67,
   68,
   69,
   70,
   71,
   72,
   73,
   74,
   75,
   76,
   77,
   78,
   79,
   80,
   81,
   82,
   83,
   84,
   85,
   86,
   87,
   88,
   89,
   90,
   91,
   92,
   93,
   94,
   95,
   96,
   97,
   98,
   99,
   100]}}

In [15]:
unique_combinations

{'RSI': [{'period': 1},
  {'period': 2},
  {'period': 3},
  {'period': 4},
  {'period': 5},
  {'period': 6},
  {'period': 7},
  {'period': 8},
  {'period': 9},
  {'period': 10},
  {'period': 11},
  {'period': 12},
  {'period': 13},
  {'period': 14},
  {'period': 15},
  {'period': 16},
  {'period': 17},
  {'period': 18},
  {'period': 19},
  {'period': 20},
  {'period': 21},
  {'period': 22},
  {'period': 23},
  {'period': 24},
  {'period': 25},
  {'period': 26},
  {'period': 27},
  {'period': 28},
  {'period': 29},
  {'period': 30},
  {'period': 31},
  {'period': 32},
  {'period': 33},
  {'period': 34},
  {'period': 35},
  {'period': 36},
  {'period': 37},
  {'period': 38},
  {'period': 39},
  {'period': 40},
  {'period': 41},
  {'period': 42},
  {'period': 43},
  {'period': 44},
  {'period': 45},
  {'period': 46},
  {'period': 47},
  {'period': 48},
  {'period': 49},
  {'period': 50},
  {'period': 51},
  {'period': 52},
  {'period': 53},
  {'period': 54},
  {'period': 55},
  {'period': 56},
  {'period': 57},
  {'period': 58},
  {'period': 59},
  {'period': 60},
  {'period': 61},
  {'period': 62},
  {'period': 63},
  {'period': 64},
  {'period': 65},
  {'period': 66},
  {'period': 67},
  {'period': 68},
  {'period': 69},
  {'period': 70},
  {'period': 71},
  {'period': 72},
  {'period': 73},
  {'period': 74},
  {'period': 75},
  {'period': 76},
  {'period': 77},
  {'period': 78},
  {'period': 79},
  {'period': 80},
  {'period': 81},
  {'period': 82},
  {'period': 83},
  {'period': 84},
  {'period': 85},
  {'period': 86},
  {'period': 87},
  {'period': 88},
  {'period': 89},
  {'period': 90},
  {'period': 91},
  {'period': 92},
  {'period': 93},
  {'period': 94},
  {'period': 95},
  {'period': 96},
  {'period': 97},
  {'period': 98},
  {'period': 99},
  {'period': 100}],
 'MACD': [{'short_period': 1, 'long_period': 1, 'signal_period': 1},
  {'short_period': 1, 'long_period': 1, 'signal_period': 2},
  {'short_period': 1, 'long_period': 1, 'signal_period': 3},
  {'short_period': 1, 'long_period': 1, 'signal_period': 4},
  {'short_period': 1, 'long_period': 1, 'signal_period': 5},
  {'short_period': 1, 'long_period': 1, 'signal_period': 6},
  {'short_period': 1, 'long_period': 1, 'signal_period': 7},
  {'short_period': 1, 'long_period': 1, 'signal_period': 8},
  {'short_period': 1, 'long_period': 1, 'signal_period': 9},
  {'short_period': 1, 'long_period': 1, 'signal_period': 10},
  {'short_period': 1, 'long_period': 1, 'signal_period': 11},
  {'short_period': 1, 'long_period': 1, 'signal_period': 12},
  {'short_period': 1, 'long_period': 1, 'signal_period': 13},
  {'short_period': 1, 'long_period': 1, 'signal_period': 14},
  {'short_period': 1, 'long_period': 1, 'signal_period': 15},
  {'short_period': 1, 'long_period': 1, 'signal_period': 16},
  {'short_period': 1, 'long_period': 1, 'signal_period': 17},
  {'short_period': 1, 'long_period': 1, 'signal_period': 18},
  {'short_period': 1, 'long_period': 1, 'signal_period': 19},
  {'short_period': 1, 'long_period': 1, 'signal_period': 20},
  {'short_period': 1, 'long_period': 1, 'signal_period': 21},
  {'short_period': 1, 'long_period': 1, 'signal_period': 22},
  {'short_period': 1, 'long_period': 1, 'signal_period': 23},
  {'short_period': 1, 'long_period': 1, 'signal_period': 24},
  {'short_period': 1, 'long_period': 1, 'signal_period': 25},
  {'short_period': 1, 'long_period': 1, 'signal_period': 26},
  {'short_period': 1, 'long_period': 1, 'signal_period': 27},
  {'short_period': 1, 'long_period': 1, 'signal_period': 28},
  {'short_period': 1, 'long_period': 1, 'signal_period': 29},
  {'short_period': 1, 'long_period': 1, 'signal_period': 30},
  {'short_period': 1, 'long_period': 1, 'signal_period': 31},
  {'short_period': 1, 'long_period': 1, 'signal_period': 32},
  {'short_period': 1, 'long_period': 1, 'signal_period': 33},
  {'short_period': 1, 'long_period': 1, 'signal_period': 34},
  {'short_period': 1, 'long_period': 1, 'signal_period': 35},
  {'short_period': 1, 'long_period': 1, 'signal_period': 36},
  {'short_period': 1, 'long_period': 1, 'signal_period': 37},
  {'short_period': 1, 'long_period': 1, 'signal_period': 38},
  {'short_period': 1, 'long_period': 1, 'signal_period': 39},
  {'short_period': 1, 'long_period': 1, 'signal_period': 40},
  {'short_period': 1, 'long_period': 1, 'signal_period': 41},
  {'short_period': 1, 'long_period': 1, 'signal_period': 42},
  {'short_period': 1, 'long_period': 1, 'signal_period': 43},
  {'short_period': 1, 'long_period': 1, 'signal_period': 44},
  {'short_period': 1, 'long_period': 1, 'signal_period': 45},
  {'short_period': 1, 'long_period': 1, 'signal_period': 46},
  {'short_period': 1, 'long_period': 1, 'signal_period': 47},
  {'short_period': 1, 'long_period': 1, 'signal_period': 48},
  {'short_period': 1, 'long_period': 1, 'signal_period': 49},
  {'short_period': 1, 'long_period': 1, 'signal_period': 50},
  {'short_period': 1, 'long_period': 1, 'signal_period': 51},
  {'short_period': 1, 'long_period': 1, 'signal_period': 52},
  {'short_period': 1, 'long_period': 1, 'signal_period': 53},
  {'short_period': 1, 'long_period': 1, 'signal_period': 54},
  {'short_period': 1, 'long_period': 1, 'signal_period': 55},
  {'short_period': 1, 'long_period': 1, 'signal_period': 56},
  {'short_period': 1, 'long_period': 1, 'signal_period': 57},
  {'short_period': 1, 'long_period': 1, 'signal_period': 58},
  {'short_period': 1, 'long_period': 1, 'signal_period': 59},
  {'short_period': 1, 'long_period': 1, 'signal_period': 60},
  {'short_period': 1, 'long_period': 1, 'signal_period': 61},
  {'short_period': 1, 'long_period': 1, 'signal_period': 62},
  {'short_period': 1, 'long_period': 1, 'signal_period': 63},
  {'short_period': 1, 'long_period': 1, 'signal_period': 64},
  {'short_period': 1, 'long_period': 1, 'signal_period': 65},
  {'short_period': 1, 'long_period': 1, 'signal_period': 66},
  {'short_period': 1, 'long_period': 1, 'signal_period': 67},
  {'short_period': 1, 'long_period': 1, 'signal_period': 68},
  {'short_period': 1, 'long_period': 1, 'signal_period': 69},
  {'short_period': 1, 'long_period': 1, 'signal_period': 70},
  {'short_period': 1, 'long_period': 1, 'signal_period': 71},
  {'short_period': 1, 'long_period': 1, 'signal_period': 72},
  {'short_period': 1, 'long_period': 1, 'signal_period': 73},
  {'short_period': 1, 'long_period': 1, 'signal_period': 74},
  {'short_period': 1, 'long_period': 1, 'signal_period': 75},
  {'short_period': 1, 'long_period': 1, 'signal_period': 76},
  {'short_period': 1, 'long_period': 1, 'signal_period': 77},
  {'short_period': 1, 'long_period': 1, 'signal_period': 78},
  {'short_period': 1, 'long_period': 1, 'signal_period': 79},
  {'short_period': 1, 'long_period': 1, 'signal_period': 80},
  {'short_period': 1, 'long_period': 1, 'signal_period': 81},
  {'short_period': 1, 'long_period': 1, 'signal_period': 82},
  {'short_period': 1, 'long_period': 1, 'signal_period': 83},
  {'short_period': 1, 'long_period': 1, 'signal_period': 84},
  {'short_period': 1, 'long_period': 1, 'signal_period': 85},
  {'short_period': 1, 'long_period': 1, 'signal_period': 86},
  {'short_period': 1, 'long_period': 1, 'signal_period': 87},
  {'short_period': 1, 'long_period': 1, 'signal_period': 88},
  {'short_period': 1, 'long_period': 1, 'signal_period': 89},
  {'short_period': 1, 'long_period': 1, 'signal_period': 90},
  {'short_period': 1, 'long_period': 1, 'signal_period': 91},
  {'short_period': 1, 'long_period': 1, 'signal_period': 92},
  {'short_period': 1, 'long_period': 1, 'signal_period': 93},
  {'short_period': 1, 'long_period': 1, 'signal_period': 94},
  {'short_period': 1, 'long_period': 1, 'signal_period': 95},
  {'short_period': 1, 'long_period': 1, 'signal_period': 96},
  {'short_period': 1, 'long_period': 1, 'signal_period': 97},
  {'short_period': 1, 'long_period': 1, 'signal_period': 98},
  {'short_period': 1, 'long_period': 1, 'signal_period': 99},
  {'short_period': 1, 'long_period': 1, 'signal_period': 100},
  {'short_period': 1, 'long_period': 2, 'signal_period': 1},
  {'short_period': 1, 'long_period': 2, 'signal_period': 2},
  {'short_period': 1, 'long_period': 2, 'signal_period': 3},
  {'short_period': 1, 'long_period': 2, 'signal_period': 4},
  {'short_period': 1, 'long_period': 2, 'signal_period': 5},
  {'short_period': 1, 'long_period': 2, 'signal_period': 6},
  {'short_period': 1, 'long_period': 2, 'signal_period': 7},
  {'short_period': 1, 'long_period': 2, 'signal_period': 8},
  {'short_period': 1, 'long_period': 2, 'signal_period': 9},
  {'short_period': 1, 'long_period': 2, 'signal_period': 10},
  {'short_period': 1, 'long_period': 2, 'signal_period': 11},
  {'short_period': 1, 'long_period': 2, 'signal_period': 12},
  {'short_period': 1, 'long_period': 2, 'signal_period': 13},
  {'short_period': 1, 'long_period': 2, 'signal_period': 14},
  {'short_period': 1, 'long_period': 2, 'signal_period': 15},
  {'short_period': 1, 'long_period': 2, 'signal_period': 16},
  {'short_period': 1, 'long_period': 2, 'signal_period': 17},
  {'short_period': 1, 'long_period': 2, 'signal_period': 18},
  {'short_period': 1, 'long_period': 2, 'signal_period': 19},
  {'short_period': 1, 'long_period': 2, 'signal_period': 20},
  {'short_period': 1, 'long_period': 2, 'signal_period': 21},
  {'short_period': 1, 'long_period': 2, 'signal_period': 22},
  {'short_period': 1, 'long_period': 2, 'signal_period': 23},
  {'short_period': 1, 'long_period': 2, 'signal_period': 24},
  {'short_period': 1, 'long_period': 2, 'signal_period': 25},
  {'short_period': 1, 'long_period': 2, 'signal_period': 26},
  {'short_period': 1, 'long_period': 2, 'signal_period': 27},
  {'short_period': 1, 'long_period': 2, 'signal_period': 28},
  {'short_period': 1, 'long_period': 2, 'signal_period': 29},
  {'short_period': 1, 'long_period': 2, 'signal_period': 30},
  {'short_period': 1, 'long_period': 2, 'signal_period': 31},
  {'short_period': 1, 'long_period': 2, 'signal_period': 32},
  {'short_period': 1, 'long_period': 2, 'signal_period': 33},
  {'short_period': 1, 'long_period': 2, 'signal_period': 34},
  {'short_period': 1, 'long_period': 2, 'signal_period': 35},
  {'short_period': 1, 'long_period': 2, 'signal_period': 36},
  {'short_period': 1, 'long_period': 2, 'signal_period': 37},
  {'short_period': 1, 'long_period': 2, 'signal_period': 38},
  {'short_period': 1, 'long_period': 2, 'signal_period': 39},
  {'short_period': 1, 'long_period': 2, 'signal_period': 40},
  {'short_period': 1, 'long_period': 2, 'signal_period': 41},
  {'short_period': 1, 'long_period': 2, 'signal_period': 42},
  {'short_period': 1, 'long_period': 2, 'signal_period': 43},
  {'short_period': 1, 'long_period': 2, 'signal_period': 44},
  {'short_period': 1, 'long_period': 2, 'signal_period': 45},
  {'short_period': 1, 'long_period': 2, 'signal_period': 46},
  {'short_period': 1, 'long_period': 2, 'signal_period': 47},
  {'short_period': 1, 'long_period': 2, 'signal_period': 48},
  {'short_period': 1, 'long_period': 2, 'signal_period': 49},
  {'short_period': 1, 'long_period': 2, 'signal_period': 50},
  {'short_period': 1, 'long_period': 2, 'signal_period': 51},
  {'short_period': 1, 'long_period': 2, 'signal_period': 52},
  {'short_period': 1, 'long_period': 2, 'signal_period': 53},
  {'short_period': 1, 'long_period': 2, 'signal_period': 54},
  {'short_period': 1, 'long_period': 2, 'signal_period': 55},
  {'short_period': 1, 'long_period': 2, 'signal_period': 56},
  {'short_period': 1, 'long_period': 2, 'signal_period': 57},
  {'short_period': 1, 'long_period': 2, 'signal_period': 58},
  {'short_period': 1, 'long_period': 2, 'signal_period': 59},
  {'short_period': 1, 'long_period': 2, 'signal_period': 60},
  {'short_period': 1, 'long_period': 2, 'signal_period': 61},
  {'short_period': 1, 'long_period': 2, 'signal_period': 62},
  {'short_period': 1, 'long_period': 2, 'signal_period': 63},
  {'short_period': 1, 'long_period': 2, 'signal_period': 64},
  {'short_period': 1, 'long_period': 2, 'signal_period': 65},
  {'short_period': 1, 'long_period': 2, 'signal_period': 66},
  {'short_period': 1, 'long_period': 2, 'signal_period': 67},
  {'short_period': 1, 'long_period': 2, 'signal_period': 68},
  {'short_period': 1, 'long_period': 2, 'signal_period': 69},
  {'short_period': 1, 'long_period': 2, 'signal_period': 70},
  {'short_period': 1, 'long_period': 2, 'signal_period': 71},
  {'short_period': 1, 'long_period': 2, 'signal_period': 72},
  {'short_period': 1, 'long_period': 2, 'signal_period': 73},
  {'short_period': 1, 'long_period': 2, 'signal_period': 74},
  {'short_period': 1, 'long_period': 2, 'signal_period': 75},
  {'short_period': 1, 'long_period': 2, 'signal_period': 76},
  {'short_period': 1, 'long_period': 2, 'signal_period': 77},
  {'short_period': 1, 'long_period': 2, 'signal_period': 78},
  {'short_period': 1, 'long_period': 2, 'signal_period': 79},
  {'short_period': 1, 'long_period': 2, 'signal_period': 80},
  {'short_period': 1, 'long_period': 2, 'signal_period': 81},
  {'short_period': 1, 'long_period': 2, 'signal_period': 82},
  {'short_period': 1, 'long_period': 2, 'signal_period': 83},
  {'short_period': 1, 'long_period': 2, 'signal_period': 84},
  {'short_period': 1, 'long_period': 2, 'signal_period': 85},
  {'short_period': 1, 'long_period': 2, 'signal_period': 86},
  {'short_period': 1, 'long_period': 2, 'signal_period': 87},
  {'short_period': 1, 'long_period': 2, 'signal_period': 88},
  {'short_period': 1, 'long_period': 2, 'signal_period': 89},
  {'short_period': 1, 'long_period': 2, 'signal_period': 90},
  {'short_period': 1, 'long_period': 2, 'signal_period': 91},
  {'short_period': 1, 'long_period': 2, 'signal_period': 92},
  {'short_period': 1, 'long_period': 2, 'signal_period': 93},
  {'short_period': 1, 'long_period': 2, 'signal_period': 94},
  {'short_period': 1, 'long_period': 2, 'signal_period': 95},
  {'short_period': 1, 'long_period': 2, 'signal_period': 96},
  {'short_period': 1, 'long_period': 2, 'signal_period': 97},
  {'short_period': 1, 'long_period': 2, 'signal_period': 98},
  {'short_period': 1, 'long_period': 2, 'signal_period': 99},
  {'short_period': 1, 'long_period': 2, 'signal_period': 100},
  {'short_period': 1, 'long_period': 3, 'signal_period': 1},
  {'short_period': 1, 'long_period': 3, 'signal_period': 2},
  {'short_period': 1, 'long_period': 3, 'signal_period': 3},
  {'short_period': 1, 'long_period': 3, 'signal_period': 4},
  {'short_period': 1, 'long_period': 3, 'signal_period': 5},
  {'short_period': 1, 'long_period': 3, 'signal_period': 6},
  {'short_period': 1, 'long_period': 3, 'signal_period': 7},
  {'short_period': 1, 'long_period': 3, 'signal_period': 8},
  {'short_period': 1, 'long_period': 3, 'signal_period': 9},
  {'short_period': 1, 'long_period': 3, 'signal_period': 10},
  {'short_period': 1, 'long_period': 3, 'signal_period': 11},
  {'short_period': 1, 'long_period': 3, 'signal_period': 12},
  {'short_period': 1, 'long_period': 3, 'signal_period': 13},
  {'short_period': 1, 'long_period': 3, 'signal_period': 14},
  {'short_period': 1, 'long_period': 3, 'signal_period': 15},
  {'short_period': 1, 'long_period': 3, 'signal_period': 16},
  {'short_period': 1, 'long_period': 3, 'signal_period': 17},
  {'short_period': 1, 'long_period': 3, 'signal_period': 18},
  {'short_period': 1, 'long_period': 3, 'signal_period': 19},
  {'short_period': 1, 'long_period': 3, 'signal_period': 20},
  {'short_period': 1, 'long_period': 3, 'signal_period': 21},
  {'short_period': 1, 'long_period': 3, 'signal_period': 22},
  {'short_period': 1, 'long_period': 3, 'signal_period': 23},
  {'short_period': 1, 'long_period': 3, 'signal_period': 24},
  {'short_period': 1, 'long_period': 3, 'signal_period': 25},
  {'short_period': 1, 'long_period': 3, 'signal_period': 26},
  {'short_period': 1, 'long_period': 3, 'signal_period': 27},
  {'short_period': 1, 'long_period': 3, 'signal_period': 28},
  {'short_period': 1, 'long_period': 3, 'signal_period': 29},
  {'short_period': 1, 'long_period': 3, 'signal_period': 30},
  {'short_period': 1, 'long_period': 3, 'signal_period': 31},
  {'short_period': 1, 'long_period': 3, 'signal_period': 32},
  {'short_period': 1, 'long_period': 3, 'signal_period': 33},
  {'short_period': 1, 'long_period': 3, 'signal_period': 34},
  {'short_period': 1, 'long_period': 3, 'signal_period': 35},
  {'short_period': 1, 'long_period': 3, 'signal_period': 36},
  {'short_period': 1, 'long_period': 3, 'signal_period': 37},
  {'short_period': 1, 'long_period': 3, 'signal_period': 38},
  {'short_period': 1, 'long_period': 3, 'signal_period': 39},
  {'short_period': 1, 'long_period': 3, 'signal_period': 40},
  {'short_period': 1, 'long_period': 3, 'signal_period': 41},
  {'short_period': 1, 'long_period': 3, 'signal_period': 42},
  {'short_period': 1, 'long_period': 3, 'signal_period': 43},
  {'short_period': 1, 'long_period': 3, 'signal_period': 44},
  {'short_period': 1, 'long_period': 3, 'signal_period': 45},
  {'short_period': 1, 'long_period': 3, 'signal_period': 46},
  {'short_period': 1, 'long_period': 3, 'signal_period': 47},
  {'short_period': 1, 'long_period': 3, 'signal_period': 48},
  {'short_period': 1, 'long_period': 3, 'signal_period': 49},
  {'short_period': 1, 'long_period': 3, 'signal_period': 50},
  {'short_period': 1, 'long_period': 3, 'signal_period': 51},
  {'short_period': 1, 'long_period': 3, 'signal_period': 52},
  {'short_period': 1, 'long_period': 3, 'signal_period': 53},
  {'short_period': 1, 'long_period': 3, 'signal_period': 54},
  {'short_period': 1, 'long_period': 3, 'signal_period': 55},
  {'short_period': 1, 'long_period': 3, 'signal_period': 56},
  {'short_period': 1, 'long_period': 3, 'signal_period': 57},
  {'short_period': 1, 'long_period': 3, 'signal_period': 58},
  {'short_period': 1, 'long_period': 3, 'signal_period': 59},
  {'short_period': 1, 'long_period': 3, 'signal_period': 60},
  {'short_period': 1, 'long_period': 3, 'signal_period': 61},
  {'short_period': 1, 'long_period': 3, 'signal_period': 62},
  {'short_period': 1, 'long_period': 3, 'signal_period': 63},
  {'short_period': 1, 'long_period': 3, 'signal_period': 64},
  {'short_period': 1, 'long_period': 3, 'signal_period': 65},
  {'short_period': 1, 'long_period': 3, 'signal_period': 66},
  {'short_period': 1, 'long_period': 3, 'signal_period': 67},
  {'short_period': 1, 'long_period': 3, 'signal_period': 68},
  {'short_period': 1, 'long_period': 3, 'signal_period': 69},
  {'short_period': 1, 'long_period': 3, 'signal_period': 70},
  {'short_period': 1, 'long_period': 3, 'signal_period': 71},
  {'short_period': 1, 'long_period': 3, 'signal_period': 72},
  {'short_period': 1, 'long_period': 3, 'signal_period': 73},
  {'short_period': 1, 'long_period': 3, 'signal_period': 74},
  {'short_period': 1, 'long_period': 3, 'signal_period': 75},
  {'short_period': 1, 'long_period': 3, 'signal_period': 76},
  {'short_period': 1, 'long_period': 3, 'signal_period': 77},
  {'short_period': 1, 'long_period': 3, 'signal_period': 78},
  {'short_period': 1, 'long_period': 3, 'signal_period': 79},
  {'short_period': 1, 'long_period': 3, 'signal_period': 80},
  {'short_period': 1, 'long_period': 3, 'signal_period': 81},
  {'short_period': 1, 'long_period': 3, 'signal_period': 82},
  {'short_period': 1, 'long_period': 3, 'signal_period': 83},
  {'short_period': 1, 'long_period': 3, 'signal_period': 84},
  {'short_period': 1, 'long_period': 3, 'signal_period': 85},
  {'short_period': 1, 'long_period': 3, 'signal_period': 86},
  {'short_period': 1, 'long_period': 3, 'signal_period': 87},
  {'short_period': 1, 'long_period': 3, 'signal_period': 88},
  {'short_period': 1, 'long_period': 3, 'signal_period': 89},
  {'short_period': 1, 'long_period': 3, 'signal_period': 90},
  {'short_period': 1, 'long_period': 3, 'signal_period': 91},
  {'short_period': 1, 'long_period': 3, 'signal_period': 92},
  {'short_period': 1, 'long_period': 3, 'signal_period': 93},

In [17]:
df.head(100)

,parameters,indicator_value,indicator_name
0,{'period': 1},0 NaN 1 0.0 2 100.0 3 ...,RSI
1,{'period': 2},0 NaN 1 0.000000 2 28...,RSI
2,{'period': 3},0 NaN 1 NaN 2 28...,RSI
3,{'period': 4},0 NaN 1 NaN 2 ...,RSI
4,{'period': 5},0 NaN 1 NaN 2 ...,RSI
...,...,...,...
95,{'period': 96},0 NaN 1 NaN 2 ...,RSI
96,{'period': 97},0 NaN 1 NaN 2 ...,RSI
97,{'period': 98},0 NaN 1 NaN 2 ...,RSI
98,{'period': 99},0 NaN 1 NaN 2 ...,RSI
99,{'period': 100},0 NaN 1 NaN 2 ...,RSI

In [22]:
!pip install --upgrade pandas_ta
!pip install --upgrade pandas numpy

Requirement already satisfied: pandas_ta in /Users/mini/Desktop/Projects/FinDRL/.venv/lib/python3.11/site-packages (0.3.14b0)
Requirement already satisfied: pandas in /Users/mini/Desktop/Projects/FinDRL/.venv/lib/python3.11/site-packages (from pandas_ta) (2.2.3)
Requirement already satisfied: numpy>=1.23.2 in /Users/mini/Desktop/Projects/FinDRL/.venv/lib/python3.11/site-packages (from pandas->pandas_ta) (2.2.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/mini/Desktop/Projects/FinDRL/.venv/lib/python3.11/site-packages (from pandas->pandas_ta) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/mini/Desktop/Projects/FinDRL/.venv/lib/python3.11/site-packages (from pandas->pandas_ta) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/mini/Desktop/Projects/FinDRL/.venv/lib/python3.11/site-packages (from pandas->pandas_ta) (2025.1)
Requirement already satisfied: six>=1.5 in /Users/mini/Desktop/Projects/FinDRL/.venv/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas->pandas_ta) (1.17.0)
Requirement already satisfied: pandas in /Users/mini/Desktop/Projects/FinDRL/.venv/lib/python3.11/site-packages (2.2.3)
Requirement already satisfied: numpy in /Users/mini/Desktop/Projects/FinDRL/.venv/lib/python3.11/site-packages (2.2.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/mini/Desktop/Projects/FinDRL/.venv/lib/python3.11/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/mini/Desktop/Projects/FinDRL/.venv/lib/python3.11/site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/mini/Desktop/Projects/FinDRL/.venv/lib/python3.11/site-packages (from pandas) (2025.1)
Requirement already satisfied: six>=1.5 in /Users/mini/Desktop/Projects/FinDRL/.venv/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [23]:
import pandas as pd
import pandas_ta as ta

from numpy import NaN as npNaN

npNaN = np.nan

ImportError: cannot import name 'NaN' from 'numpy' (/Users/mini/Desktop/Projects/FinDRL/.venv/lib/python3.11/site-packages/numpy/__init__.py)

In [20]:
class RSI(Indicator):
    def __init__(self, period=14):
        self.period = period

    def calculate(self, data: pd.DataFrame) -> pd.Series:
        return ta.rsi(data['Close'], length=self.period)

NameError: name 'Indicator' is not defined